### ISSUE TITLE
modbus plugin compilation with g++ 4.8.2

### ISSUE THREAD

**Issue by gempa-jabe** [SeisComP/seedlink#4]
The plugin does not compile with g++ 4.8.2 under Redhat 7.

```
src/base/seedlink/plugins/serial_plugin/proto_modbus.cc:332:25: error: ‘defaultfloat’ was not declared in this scope
```

The `defaultfloat` manipulator is available with C++11 and not supported with this g++ version.

**Comment by andres-h** [comment]
fixed with https://github.com/SeisComP/seedlink/commit/d1a548d46223d210aee9636b194eb725741b78dc
